name: Java at_client CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        working-directory: at_client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 8 and maven cache
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Build clean and run unit tests
        run: mvn --batch-mode clean test -DskipIntegrationTests=true -Dgpg.skip=true
      - name: Run integration tests
        run: mvn --batch-mode verify -DskipUnitTests=true -Dgpg.skip=true
      - name: Generate build outputs
        run: mvn --batch-mode install -DskipTests=true --update-snapshots --no-transfer-progress -Dgpg.skip=true
