# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Deploy `at_client` to Nexus OSSRH

on:
  push:
    branches:
      - trunk
      - maven-dependency
  
jobs:
  build:
    defaults:
      run:
        working-directory: at_client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}/at_client/ # location for the settings.xml file

    - name: Publish to Nexus OSSRH
      run: mvn deploy -s $GITHUB_WORKSPACE/at_client/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}