# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Deploy `at_client` to Nexus OSSRH

on:
  push:
    branches:
      - trunk
      - maven-dependency
  
jobs:
  deploy:
    defaults:
      run:
        working-directory: at_client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        overwrite-settings: true
        settings-path: ./at_client # location for the settings.xml file
        server-username: "$MAVEN_USERNAME" # env variable for username in deploy
        server-password: "$MAVEN_PASSWORD" # env variable for token in deploy
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: "$GPG_PASSPHRASE" # env variable for GPG private key passphrase
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Print folder
      run: head -n 2 ./at_client/settings.xml

    - name: Publish to Apache Maven Central
      run: |
        mvn \
        deploy \
        --batch-mode \
        --no-transfer-progress \
        -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
        -s ./at_client/settings.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}