name: Maven Deploy `at_client` to Nexus OSSRH

on:
  push:
    branches:
      - trunk

permissions:
  contents: read

jobs:
  deploy:
    defaults:
      run:
        working-directory: at_client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: ossrh
        server-username: ${{ secrets.MAVEN_USERNAME }}
        server-password: ${{ secrets.MAVEN_PASSWORD }}

    - name: Import GPG key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import --no-tty --yes
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: List GPG keys
      run: |
        gpg --list-secret-keys --keyid-format LONG

    - name: Publish to Apache Maven Central
      run: |
        mvn install deploy \
          --batch-mode \
          --no-transfer-progress \
          -Dgpg.skip=false \
          -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
