name: Maven Deploy `at_client` to Nexus OSSRH

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

permissions:
  contents: read

jobs:
  deploy:
    defaults:
      run:
        working-directory: at_client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set up JDK 8
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: "8"
          distribution: "adopt"
          server-id: ossrh
          server-username: ${{ secrets.MAVEN_USERNAME }}
          server-password: ${{ secrets.MAVEN_PASSWORD }}

      - name: Print folder
        run: ls -al .

      - name: Print m2 settings
        continue-on-error: true
        run: cat ~/.m2/settings.xml

      - name: Publish to Apache Maven Central
        run: |
          mvn \
          install \
          org.apache.maven.plugins:maven-deploy-plugin:deploy \
          --batch-mode \
          --no-transfer-progress \
          -Dgpg.skip=false -e
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
